<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_kategori extends CI_Model
{

    public $table = 'm_kategori';
    public $id = 'uniqid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('uniqid,id_kategori,nama_kategori,urutan,isi');
        $this->datatables->from('m_kategori');
        //add this line for join
        //$this->datatables->join('table2', 'm_kategori.field = table2.field');
        $this->datatables->add_column('action', anchor(base_url('m_kategori/read/$1'),'Read')." | ".anchor(base_url('m_kategori/update/$1'),'Update')." | ".anchor(base_url('m_kategori/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'uniqid');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	$this->db->or_like('urutan', $q);
	$this->db->or_like('isi', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('nama_kategori', $q);
	$this->db->or_like('urutan', $q);
	$this->db->or_like('isi', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_kategori.php */
/* Location: ./application/models/Model_kategori.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-02-02 07:57:08 */
/* http://harviacode.com */