<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_product extends CI_Model
{

    public $table = 'm_product';
    public $id = 'uniqid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('a.uniqid,id_product,b.nama_kategori as id_kategori,c.nama_jenis as id_jenis,nama_product,harga,deskripsi,gambar,discount,tgl_dibuat,user_pembuat,status');
        $this->datatables->from('m_product a');
        $this->datatables->join('m_kategori b','a.id_kategori=b.id_kategori');
        $this->datatables->join('m_jenis c','a.id_jenis=c.id_jenis');
        //add this line for join
        //$this->datatables->join('table2', 'm_product.field = table2.field');
        $this->datatables->add_column('action', anchor(base_url('m_product/read/$1'),'Read')." | ".anchor(base_url('m_product/update/$1'),'Update')." | ".anchor(base_url('m_product/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'uniqid');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('nama_product', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('tgl_dibuat', $q);
	$this->db->or_like('user_pembuat', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('uniqid', $q);
	$this->db->or_like('id_product', $q);
	$this->db->or_like('id_kategori', $q);
	$this->db->or_like('id_jenis', $q);
	$this->db->or_like('nama_product', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('deskripsi', $q);
	$this->db->or_like('gambar', $q);
	$this->db->or_like('discount', $q);
	$this->db->or_like('tgl_dibuat', $q);
	$this->db->or_like('user_pembuat', $q);
	$this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->set("uniqid",'UUID()',FALSE);
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_product.php */
/* Location: ./application/models/Model_product.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-27 09:43:23 */
/* http://harviacode.com */