<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_metode_pembayaran extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Model_metode_pembayaran');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
       
    }
    public $nama_template='template_admin';

    public function index()
    {
        $this->template->load($this->nama_template,'m_metode_pembayaran/m_metode_pembayaran_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Model_metode_pembayaran->json();
    }

    public function read($id) 
    {
        $row = $this->Model_metode_pembayaran->get_by_id($id);
        if ($row) {
            $data = array(
		'id_metode' => $row->id_metode,
		'nama_metode' => $row->nama_metode,
	    );
            $this->template->load($this->nama_template,'m_metode_pembayaran/m_metode_pembayaran_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('m_metode_pembayaran'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Tambah',
            'action' => base_url('m_metode_pembayaran/create_action'),
	    'id_metode' => set_value('id_metode'),
	    'nama_metode' => set_value('nama_metode'),
	);
        $this->template->load($this->nama_template,'m_metode_pembayaran/m_metode_pembayaran_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'nama_metode' => $this->input->post('nama_metode',TRUE),
	    );

            $this->Model_metode_pembayaran->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success');
            redirect(base_url('m_metode_pembayaran'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Model_metode_pembayaran->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Ubah',
                'action' => base_url('m_metode_pembayaran/update_action'),
		'id_metode' => set_value('id_metode', $row->id_metode),
		'nama_metode' => set_value('nama_metode', $row->nama_metode),
	    );
            $this->template->load($this->nama_template,'m_metode_pembayaran/m_metode_pembayaran_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('m_metode_pembayaran'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_metode', TRUE));
        } else {
            $data = array(
		'nama_metode' => $this->input->post('nama_metode',TRUE),
	    );

            $this->Model_metode_pembayaran->update($this->input->post('id_metode', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(base_url('m_metode_pembayaran'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Model_metode_pembayaran->get_by_id($id);

        if ($row) {
            $this->Model_metode_pembayaran->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(base_url('m_metode_pembayaran'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(base_url('m_metode_pembayaran'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('nama_metode', 'nama metode', 'trim|required');

	$this->form_validation->set_rules('id_metode', 'id_metode', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file M_metode_pembayaran.php */
/* Location: ./application/controllers/M_metode_pembayaran.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-01-31 04:25:05 */
/* http://harviacode.com */